name: Secrets Scan
on:
  pull_request: { branches: [main] }
  push: { branches: [main] }
  schedule:
    - cron: "0 7 * * 1" # weekly baseline
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  titus:
    uses: N3m3s1sGr0up/org-workflows/.github/workflows/titus-scan.yml@57bb1576e9c6c807feaa398bd60aeb27fa9a81ed # v0.1.0
    permissions:
      contents: read
      security-events: write
      actions: read
    secrets: inherit
