name: Secrets Scan
on:
  pull_request: { branches: [main] }
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  secrets-scan:
    uses: ./.github/workflows/_secrets-scan-reusable.yml
    permissions:
      contents: read
